#!/usr/bin/env python3

import serial

ser = serial.Serial('COM4', baudrate = 9600, timeout = 1)

if __name__ == '__main__':

    while 1:
        arduinoData = ser.readline()
        print(arduinoData)
